/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tb_konvert_bilangan;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class TBkonversbilangan extends javax.swing.JFrame {

    /**
     * Creates new form TBkonversbilangan
     */
    public TBkonversbilangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        input = new javax.swing.JLabel();
        output = new javax.swing.JLabel();
        bilangan_dari = new javax.swing.JComboBox<>();
        bilangan_ke = new javax.swing.JComboBox<>();
        input_bilangan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        output_bilangan = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Konversi Bilanggan");

        jLabel2.setText("Dari :");

        input.setText("Memasukan Angka");
        input.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                inputAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        output.setText("Hasil");

        bilangan_dari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hexadecimal", "Decimal", "Biner", "Oktal" }));
        bilangan_dari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilangan_dariActionPerformed(evt);
            }
        });

        bilangan_ke.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hexadecimal", "Decimal", "Biner", "Oktal" }));
        bilangan_ke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilangan_keActionPerformed(evt);
            }
        });

        input_bilangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_bilanganActionPerformed(evt);
            }
        });

        jLabel5.setText("Ke :");

        jButton1.setText("Konversi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("Creat by sholahuddin");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(input)
                    .addComponent(input_bilangan, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(output)
                    .addComponent(output_bilangan, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(bilangan_dari, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(bilangan_ke, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bilangan_dari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bilangan_ke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(42, 42, 42)
                .addComponent(input)
                .addGap(18, 18, 18)
                .addComponent(input_bilangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(output)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(output_bilangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_bilanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_bilanganActionPerformed
        
    }//GEN-LAST:event_input_bilanganActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            //Hexadesimal
            if(bilangan_dari.getSelectedItem()=="Hexadecimal"){
                //proses pengkonveksian
                //Hexadesimal ke Desimal
                if(bilangan_ke.getSelectedItem()=="Decimal"){
                    String hexa = input_bilangan.getText();
                    int outDes = Integer.parseInt(hexa,16);
                    output_bilangan.setText(Integer.toUnsignedString(outDes));
                }
                
                //Hexadesimal ke Biner
                else if(bilangan_ke.getSelectedItem()=="Biner"){
                    String hexa2 = input_bilangan.getText();
                    int outDes2 = Integer.parseInt(hexa2,16);
                    String hasilDes = Integer.toUnsignedString(outDes2);
                    int hasilBiner = Integer.parseInt(hasilDes);
                    output_bilangan.setText(Integer.toBinaryString(hasilBiner));
                }
            
                //Hexadesimal ke Oktal
                else if(bilangan_ke.getSelectedItem()=="Oktal"){
                    String hexa3 = input_bilangan.getText();
                    int outDes3 = Integer.parseInt(hexa3,16);
                    String hasilDes2 = Integer.toUnsignedString(outDes3);
                    int hasilOktal2 = Integer.parseInt(hasilDes2);
                    output_bilangan.setText(Integer.toOctalString(hasilOktal2));
                }
            }
            
            //Oktal
            else if(bilangan_dari.getSelectedItem()=="Oktal"){
                //Proses pengkonveksian
                //Oktal ke Desimal
                if(bilangan_ke.getSelectedItem()=="Decimal"){
                    String oktal = input_bilangan.getText();
                    int outDes3 = Integer.parseInt(oktal,8);
                    output_bilangan.setText(Integer.toUnsignedString(outDes3));
                }
                
                //Oktal ke Biner
                else if(bilangan_ke.getSelectedItem()=="Biner"){
                    String oktal2 = input_bilangan.getText();
                    int outDes4 = Integer.parseInt(oktal2,8);
                    String hasilDes2 = Integer.toUnsignedString(outDes4);
                    int hasilBiner2 = Integer.parseInt(hasilDes2);
                    output_bilangan.setText(Integer.toBinaryString(hasilBiner2));
                }
            
                //Oktal ke Hexadesimal
                else if(bilangan_ke.getSelectedItem()=="Hexadecimal"){
                    String hexa3 = input_bilangan.getText();
                    int outDes5 = Integer.parseInt(hexa3,8);
                    String hasilDes3 = Integer.toUnsignedString(outDes5);
                    int hasilHexa3 = Integer.parseInt(hasilDes3);
                    output_bilangan.setText(Integer.toHexString(hasilHexa3));
                }
            }
            
            //Biner
            else if(bilangan_dari.getSelectedItem()=="Biner"){
                //Proses pengkonveksian
                //Biner ke Desimal
                if(bilangan_ke.getSelectedItem()=="Decimal"){
                    String biner4 = input_bilangan.getText();
                    int outDes6 = Integer.parseInt(biner4,2);
                    output_bilangan.setText(Integer.toUnsignedString(outDes6));
                }
                
                //Biner ke Oktal
                else if(bilangan_ke.getSelectedItem()=="Oktal"){
                    String biner7 = input_bilangan.getText();
                    int outDes7 = Integer.parseInt(biner7,2);
                    String hasilBiner7 = Integer.toUnsignedString(outDes7);
                    int hasilOktal7 = Integer.parseInt(hasilBiner7);
                    output_bilangan.setText(Integer.toOctalString(hasilOktal7));
                }
            //zzzzzz
                //Biner ke Hexadesimal
                else if(bilangan_ke.getSelectedItem()=="Hexadecimal"){
                    String biner8 = input_bilangan.getText();
                    int outDes8 = Integer.parseInt(biner8);
                    String hasilBiner8 = Integer.toUnsignedString(outDes8);
                    int hasilHexa8 = Integer.parseInt(hasilBiner8);
                    output_bilangan.setText(Integer.toHexString(hasilHexa8));
                }
            }
            
            //Desimal
            else if(bilangan_dari.getSelectedItem()=="Decimal"){
                //Proses pengkonveksian
                //Desimal ke Oktal
                if(bilangan_ke.getSelectedItem()=="Oktal"){
                    String desimal1 = input_bilangan.getText();
                    int outOktal9 = Integer.parseInt(desimal1);
                    output_bilangan.setText(Integer.toOctalString(outOktal9));
                }
                
                //Desimal ke Biner
                else if(bilangan_ke.getSelectedItem()=="Biner"){
                    String desimal2 = input_bilangan.getText();
                    int outBiner9 = Integer.parseInt(desimal2);
                    output_bilangan.setText(Integer.toBinaryString(outBiner9));
                }
                
                //Desimal ke Hexadesimal
                else if(bilangan_ke.getSelectedItem()=="Hexadecimal"){
                    String desimal3 = input_bilangan.getText();
                    int outHexa9 = Integer.parseInt(desimal3);
                    output_bilangan.setText(Integer.toHexString(outHexa9));
                }
            }
           
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null,"Input Tidak Benar");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bilangan_dariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilangan_dariActionPerformed

    }//GEN-LAST:event_bilangan_dariActionPerformed

    private void bilangan_keActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilangan_keActionPerformed
      
    }//GEN-LAST:event_bilangan_keActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void inputAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_inputAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TBkonversbilangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TBkonversbilangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TBkonversbilangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TBkonversbilangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TBkonversbilangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bilangan_dari;
    private javax.swing.JComboBox<String> bilangan_ke;
    private javax.swing.JLabel input;
    private javax.swing.JTextField input_bilangan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel output;
    private javax.swing.JTextField output_bilangan;
    // End of variables declaration//GEN-END:variables
}
